language: php

php:
  - 7.1
  - 7.2
  - nightly

allow_failures:
  - 7.2
  - nightly

before_script:
  - mysql -e 'CREATE DATABASE southeastphp_test;'
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan migrate
  - php artisan key:generate

script:
  - phpunit

services:
  - mysql

after_success:
  curl -s "https://forge.laravel.com/servers/137357/sites/423802/deploy/http?token=XFxiCGREI4SgW2HKuxXWlbpwhqTLSq61mKat3h5S"
  echo 'all tests pass'